carto/urls.py
from django.urls import path

from . import views

app_name = "carto"


urlpatterns = [
    path("vector", views.VectorView.as_view(), name="vector"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    """Snippet to test Sentry integration"""
    division_by_zero = 1 / 0  # # noqa: F841


admin.site.site_header = f"SPARTE administration v{settings.OFFICIAL_VERSION}"


urlpatterns = [
    path("boom/", trigger_error),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("public/", include("public_data.urls")),
    path("project/", include("project.urls")),
    path("carte/", include("carto.urls")),
    path("word/", include("diagnostic_word.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    try:
        # try except required to activate debug in staging server
        # where we do not install dev dependencies
        import debug_toolbar  # noqa: E402

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

    path = settings.BASE_DIR / "htmlcov"
    urlpatterns += static("/cov/", document_root=path)

home/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .api.views import RegionViewSet

app_name = "home"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("mentions-legales", views.LegalNoticeView.as_view(), name="cgv"),
    path("confidentialité", views.PrivacyView.as_view(), name="privacy"),
    path("stats", views.StatsView.as_view(), name="stats"),
    path("test", views.TestView.as_view(), name="test"),
    path("accessibilite", views.AccessView.as_view(), name="accessibilite"),
    path("robots.txt", views.RobotView.as_view(), name="robots"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path(
        "newsletter/inscription",
        views.NewsletterSubscriptionView.as_view(),
        name="nwl-subscription",
    ),
    path(
        "newsletter/confirmation/<slug:token>",
        views.NewsLetterConfirmationView.as_view(),
        name="nwl-confirmation",
    ),
    path(
        "emails",
        views.AllEmailsView.as_view(),
        name="all-emails",
    ),
]

router = routers.DefaultRouter()
router.register(r"stats/region", RegionViewSet)
urlpatterns += router.urls

project/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views
from .api_views import EmpriseViewSet, ProjectViewSet

app_name = "project"


# See below for DRF's router inclusions

urlpatterns = [
    # ### PROJECTS ###
    # CREATE
    path("nouveau", views.CreateProjectViews.as_view(), name="create"),
    path("<int:pk>/en-construction", views.SplashScreenView.as_view(), name="splash"),
    path(
        "<int:pk>/en-construction/progress",
        views.SplashProgressionView.as_view(),
        name="splash-progress",
    ),
    # CRUD
    path("", views.ProjectListView.as_view(), name="list"),
    path("<int:pk>/", views.ProjectReportSynthesisView.as_view(), name="detail"),
    path("<int:pk>/ajouter", views.ClaimProjectView.as_view(), name="claim"),
    path("<int:pk>/edit", views.ProjectUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="delete"),
    path("<int:pk>/ajouter-voisin", views.ProjectAddLookALike.as_view(), name="lookalike"),
    path(
        "<int:pk>/retirer-voisin/<slug:public_key>",
        views.ProjectRemoveLookALike.as_view(),
        name="rm-lookalike",
    ),
    # REPORT
    path(
        "<int:pk>/tableau-de-bord/consommation",
        views.ProjectReportConsoView.as_view(),
        name="report_conso",
    ),
    path(
        "<int:pk>/tableau-de-bord/synthesis",
        views.ProjectReportSynthesisView.as_view(),
        name="report_synthesis",
    ),
    path(
        "<int:pk>/tableau-de-bord/découvrir-l-ocsge",
        views.ProjectReportDicoverOcsgeView.as_view(),
        name="report_discover",
    ),
    path(
        "<int:pk>/tableau-de-bord/usage",
        views.ProjectReportUsageView.as_view(),
        name="report_usage",
    ),
    path(
        "<int:pk>/tableau-de-bord/artificialisation",
        views.ProjectReportArtifView.as_view(),
        name="report_artif",
    ),
    path(
        "<int:pk>/tableau-de-bord/groupes-communes",
        views.ProjectReportCityGroupView.as_view(),
        name="report_city_group",
    ),
    path(
        "<int:pk>/tableau-de-bord/objectif-2031",
        views.ProjectReportTarget2031View.as_view(),
        name="report_target_2031",
    ),
    # REPORT PARTIALS
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/surface",
        views.ConsoRelativeSurfaceChart.as_view(),
        name="relative-surface",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/population",
        views.ConsoRelativePopChart.as_view(),
        name="relative-pop",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/ménages",
        views.ConsoRelativeHouseholdChart.as_view(),
        name="relative-household",
    ),
    path(
        "<int:pk>/set-target-2031",
        views.SetTargetView.as_view(),
        name="set_target_2031",
    ),
    # MAP
    path("<int:pk>/map", views.ProjectMapView.as_view(), name="map"),
    path(
        "<int:pk>/carte/comprendre-mon-artificialisation",
        views.MyArtifMapView.as_view(),
        name="theme-my-artif",
    ),
    path(
        "<int:pk>/carte/consomation-villes-du-territoire",
        views.CitySpaceConsoMapView.as_view(),
        name="theme-city-conso",
    ),
    path(
        "<int:pk>/carte/artificialisation-villes-du-territoire",
        views.CityArtifMapView.as_view(),
        name="theme-city-artif",
    ),
    # DOWNLOAD
    path(
        "<int:pk>/tableau-de-bord/telechargement",
        views.ProjectReportDownloadView.as_view(),
        name="report_download",
    ),
    path(
        "<int:request_id>/word/telechargement",
        views.DownloadWordView.as_view(),
        name="word_download",
    ),
    # EXPORT
    path("exports/", views.ExportListView.as_view(), name="excel"),
    path("<int:pk>/export-excel", views.ExportExcelView.as_view(), name="export-excel"),
    # SUB APPS
    path("<int:pk>/trajectoires", include("trajectory.urls", namespace="trajectory")),
]


# Add API urls
router = routers.DefaultRouter()
router.register(r"geojson", EmpriseViewSet)
router.register(r"projects", ProjectViewSet)


urlpatterns += router.urls

carto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from public_data.models import CouvertureSol


class VectorView(LoginRequiredMixin, TemplateView):
    template_name = "carto/vector.html"

    def get_context_data(self, **kwargs):
        kwargs["couv_sol_list"] = CouvertureSol.objects.all()
        return super().get_context_data(**kwargs)

carto/templates/carto/full_carto.html
{% extends 'index.html' %}

{% load static %}
{% load humanize %}
{% load i18n %}
{% load l10n %}
{% load sri %}

{% block pagetitle %}
Carte intéractive
{% endblock %}

{% block headers %}
<!-- leaflet -->

{% sri_static "carto/js/leaflet.js" %}
{% sri_static "carto/css/leaflet.css" %}

<style nonce="{{ CSP_NONCE }}">
.info {
    padding: 6px 8px;
    font: 14px/16px Arial, Helvetica, sans-serif;
    background: white;
    background: rgba(255,255,255,0.8);
    box-shadow: 0 0 15px rgba(0,0,0,0.2);
    border-radius: 5px;
}
.info h4 {
    margin: 0 0 5px;
    color: #777;
}
.legend {
    line-height: 18px;
    color: #555;
}
.legend i {
    width: 18px;
    height: 18px;
    float: left;
    margin-right: 8px;
    opacity: 0.7;
}
#local-container {
    overflow: auto;
}
#layer_list {
    width: 300px;
    overflow: auto;
}
#layer_title {
    width: 23px;
    font-size: 1.5rem;
}

html, body {
    height: 100% !important;
  }
</style>
{% endblock %}

{% block carto %}
<div id="local-container" class="d-flex h-100">
    <div class="collapse collapse-horizontal p-2" id="layer_list">
        <h2>Calques</h2>
    </div>
    <div id="layer_title" class="row justify-content-center h-100 border-right m-0 p-0">
        <a href="#" class="p-0 text-center" id="div-toggle-calque">
            <i class="bi bi-chevron-double-right" id="toggle-calque"></i>
            <br/><img src="{% static 'carto/img/calques-vertical.png' %}" width="18px" />
        </a>

    </div>
    <div id="mapid" class="flex-grow-1"></div>
</div>
{% endblock %}

{% block bodyend %}
{% localize off %}
{% sri_static "carto/js/map.js" %}
<script language="javascript" nonce="{{ CSP_NONCE }}">
geolayers = [
{% for layer in layer_list %}
    {
        {% for k, v in layer.items %}
        {{ k }}: "{{ v|safe }}",
        {% endfor %}
    },
{% endfor %}
]
let carto = new Carto ([{{ center_lat }}, {{ center_lng }}], {{ default_zoom }})
carto.init(geolayers)
</script>
{% endlocalize %}
{% endblock %}

{% block tagging %}

<script language="javascript" nonce="{{ CSP_NONCE }}">
var isvisible = false
$("#div-toggle-calque").click(function () {
    if (isvisible) {
        $("#layer_list").hide('slow')
        $("#toggle-calque").toggleClass('bi-chevron-double-right').toggleClass('bi-chevron-double-left');
        isvisible = false
    }else{
        $("#layer_list").show('slow', function () {})
        $("#toggle-calque").toggleClass('bi-chevron-double-right').toggleClass('bi-chevron-double-left')
        isvisible = true
    }
    let height = $(window).height() - $('.fr-header').height() - $('.fr-container').height()
    $("#layer_list").height(height)
    console.log('clicked')
})

const resize = () => {
    let height = $(window).height() - $('.fr-header').height() - $('.fr-container').height()
    console.log('test', height)
    $("#layer_list").height(height)
}

$( window ).on('load', function () {
    _paq.push(['trackEvent', 'Consultation diagnostic', 'Carte intéractive', 'ouverture'])
    resize()
})

$(window).resize(() => {
    let height = $(window).height() - $('.fr-header').height() - $('.fr-container').height()
    console.log('test', height)
    $("#layer_list").height(height)
})

</script>
{% endblock tagging %}

{% block footer %}{% endblock footer %}

carto/templates/carto/theme_map.html
{% extends 'index.html' %}

{% load static %}
{% load humanize %}
{% load i18n %}
{% load l10n %}
{% load sri %}

{% block pagetitle %}
Carte thématique - {{ map_name }}
{% endblock pagetitle %}

{% block headers %}
{% sri_static "carto/js/leaflet.js" %}
{% sri_static "carto/css/leaflet.css" %}
{% sri_static "carto/css/theme_map.css" %}
{% sri_static "carto/js/map.js" %}
<style nonce="{{ CSP_NONCE }}">
html, body {
    height: 100% !important;
}
</style>
{% endblock headers %}

{% block content %}
<div id="local-container" class="d-flex h-100">
    <div class="h-100 collapse collapse-horizontal p-2" id="map_list">
        <h2>Cartes thématiques</h2>
        <ul>
            <li><a href="{% url 'project:theme-my-artif' project.pk %}">Comprendre L'évolution de l'artificialisation de mon territoire</a></li>
            <li><a href="{% url 'project:theme-city-conso' project.pk %}">Consommation des communes de mon territoire</a></li>
            <li><a href="{% url 'project:theme-city-artif' project.pk %}">Artificialisation des communes de mon territoire</a></li>
        </ul>
    </div>
    <div id="map_title" class="row justify-content-center h-100 border-right m-0 p-0">
        <a href="#" class="p-0 text-center" data-bs-toggle="collapse" data-bs-target="#map_list" aria-expanded="false" aria-controls="map_list">
            <i class="bi bi-chevron-double-right" id="toggle-calque"></i>
        </a>
    </div>

    <div id="mapid" class="flex-grow-1"></div>
</div>
<div id="mapid" class="h-100 w-100"></div>

<div id="layer_list"></div>
{% endblock content %}

{% block footer %}{% endblock footer %}

{% block bodyend %}
{% localize off %}
<script language="javascript" nonce="{{ CSP_NONCE }}">
geolayers = [
{% for layer in layer_list %}
    {
        {% for k, v in layer.items %}
        {{ k }}: "{{ v|safe }}",
        {% endfor %}
    },
{% endfor %}
]
let carto = new Carto ([{{ center_lat }}, {{ center_lng }}], {{ default_zoom }})
carto.init(geolayers)
</script>
{% endlocalize %}
{% endblock bodyend %}

{% block tagging %}
<script language="javascript" nonce="{{ CSP_NONCE }}">
$( window ).on('load', function () {
    _paq.push(['trackEvent', 'Consultation diagnostic', 'Carte intéractive', '{{ map_name }}'])
})
</script>
{% endblock tagging %}

carto/templates/carto/vector.html
{% extends 'index.html' %}

{% load static %}
{% load humanize %}
{% load i18n %}
{% load l10n %}
{% load sri %}

{% block pagetitle %}
Carte intéractive
{% endblock %}

{% block headers %}
{% sri_static "carto/js/leaflet.js" %}
{% sri_static "carto/css/leaflet.css" %}
{% endblock %}

{% block carto %}

<div id="vectormap" class="flex-grow-1"></div>

{% endblock %}

{% block bodyend %}
{% localize off %}
<script src="https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js"></script>
<script language="javascript" nonce="{{ CSP_NONCE }}">


{% comment %} L.tileLayer(
    "https://wxs.ign.fr/ocsge/geoportail/tms/1.0.0/{identifier}/{z}/{x}/{y}.png",
    {
		minZoom : 0,
		maxZoom : 18,
        attribution : "IGN-F/Geoportail",
		tileSize : 256, // les tuiles du Géooportail font 256x256px
        identifier: "OCSGE.USAGE.2019"
	}
).addTo(lmap)  {% endcomment %}

var usage = new L.tileLayer(
    "https://wxs.ign.fr/ocsge/geoportail/tms/1.0.0/{identifier}/{z}/{x}/{y}.png",
    {
		minZoom : 6,
		maxZoom : 16,
        attribution : "IGN-F/Geoportail",
		tileSize : 256, // les tuiles du Géooportail font 256x256px
        identifier: "OCSGE.USAGE.2019",
        display: false
	}
)

var couverture = new L.tileLayer(
    // "https://wxs.ign.fr/ocsge/geoportail/tms/1.0.0/{identifier}/{z}/{x}/{y}.pbf",
    "https://vectortiles.ign.fr/rok4server/1.0.0/{identifier}/{z}/{x}/{y}.png",
    {
        minZoom : 6,
		maxZoom : 16,
        attribution : "IGN-F/Geoportail",
		tileSize : 256, // les tuiles du Géooportail font 256x256px
        identifier: "OCSGE_2019"
    }
)

couverture_style = {
    {% for couv_sol in couv_sol_list %}
    "{{ couv_sol.code_prefix }}": "{{ couv_sol.map_color }}",
    {% endfor %}
}

var vectorStyles = {
    occupation_sol: function(properties, zoom) {
        console.log(properties)
        color = couverture_style[properties.code_cs]
        if (color == "#3388fe")
        {
            return {
                weight: 1,
                color: "#ff0000",
                fillcolor: color,
                fillOpacity: 0.4,
                fill: true
            }
        }
        else
        {
            return {
                weight: 0,
                color: color,
                fillcolor: color,
                fillOpacity: 0.4,
                fill: true
            }
        }
    }
}
var couverture = L.vectorGrid.protobuf(
    "https://vectortiles.ign.fr/rok4server/1.0.0/OCSGE_GERS_2016_V2/{z}/{x}/{y}.pbf",
    {
        vectorTileLayerStyles: vectorStyles,
    }
)

var ortho = L.tileLayer(
    'https://wxs.ign.fr/{ignApiKey}/geoportail/wmts?' +
    '&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&TILEMATRIXSET=PM' +
    '&LAYER={ignLayer}&STYLE={style}&FORMAT={format}' +
    '&TILECOL={x}&TILEROW={y}&TILEMATRIX={z}', {
        attribution: '<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
        ignApiKey: 'ortho',
        ignLayer: 'ORTHOIMAGERY.ORTHOPHOTOS',
        style: 'normal',
        format: 'image/jpeg',
        service: 'WMTS'
    }
)

var lmap = new L.map(
    "vectormap",
    {
        center: new L.LatLng(43.68382284646206, 0.4771343996769177),
        zoom: 16,
        zoomControl: true,
        minZoom: 6,
        maxZoom: 16
    }
)

var baseMaps = {
    "ortho": ortho,
};

var overlayMaps = {
    "couverture": couverture,
    "usage": usage,
};

var layerControl = L.control.layers(baseMaps, overlayMaps).addTo(lmap);

</script>
{% endlocalize %}
{% endblock %}


{% block footer %}{% endblock footer %}