config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    """Snippet to test Sentry integration"""
    division_by_zero = 1 / 0  # # noqa: F841


admin.site.site_header = f"SPARTE administration v{settings.OFFICIAL_VERSION}"


urlpatterns = [
    path("boom/", trigger_error),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("public/", include("public_data.urls")),
    path("project/", include("project.urls")),
    path("carte/", include("carto.urls")),
    path("word/", include("diagnostic_word.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    try:
        # try except required to activate debug in staging server
        # where we do not install dev dependencies
        import debug_toolbar  # noqa: E402

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

    path = settings.BASE_DIR / "htmlcov"
    urlpatterns += static("/cov/", document_root=path)

home/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .api.views import RegionViewSet

app_name = "home"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("mentions-legales", views.LegalNoticeView.as_view(), name="cgv"),
    path("confidentialité", views.PrivacyView.as_view(), name="privacy"),
    path("stats", views.StatsView.as_view(), name="stats"),
    path("test", views.TestView.as_view(), name="test"),
    path("accessibilite", views.AccessView.as_view(), name="accessibilite"),
    path("robots.txt", views.RobotView.as_view(), name="robots"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path(
        "newsletter/inscription",
        views.NewsletterSubscriptionView.as_view(),
        name="nwl-subscription",
    ),
    path(
        "newsletter/confirmation/<slug:token>",
        views.NewsLetterConfirmationView.as_view(),
        name="nwl-confirmation",
    ),
    path(
        "emails",
        views.AllEmailsView.as_view(),
        name="all-emails",
    ),
]

router = routers.DefaultRouter()
router.register(r"stats/region", RegionViewSet)
urlpatterns += router.urls

project/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views
from .api_views import EmpriseViewSet, ProjectViewSet

app_name = "project"


# See below for DRF's router inclusions

urlpatterns = [
    # ### PROJECTS ###
    # CREATE
    path("nouveau", views.CreateProjectViews.as_view(), name="create"),
    path("<int:pk>/en-construction", views.SplashScreenView.as_view(), name="splash"),
    path(
        "<int:pk>/en-construction/progress",
        views.SplashProgressionView.as_view(),
        name="splash-progress",
    ),
    # CRUD
    path("", views.ProjectListView.as_view(), name="list"),
    path("<int:pk>/", views.ProjectReportSynthesisView.as_view(), name="detail"),
    path("<int:pk>/ajouter", views.ClaimProjectView.as_view(), name="claim"),
    path("<int:pk>/edit", views.ProjectUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="delete"),
    path("<int:pk>/ajouter-voisin", views.ProjectAddLookALike.as_view(), name="lookalike"),
    path(
        "<int:pk>/retirer-voisin/<slug:public_key>",
        views.ProjectRemoveLookALike.as_view(),
        name="rm-lookalike",
    ),
    # REPORT
    path(
        "<int:pk>/tableau-de-bord/consommation",
        views.ProjectReportConsoView.as_view(),
        name="report_conso",
    ),
    path(
        "<int:pk>/tableau-de-bord/synthesis",
        views.ProjectReportSynthesisView.as_view(),
        name="report_synthesis",
    ),
    path(
        "<int:pk>/tableau-de-bord/découvrir-l-ocsge",
        views.ProjectReportDicoverOcsgeView.as_view(),
        name="report_discover",
    ),
    path(
        "<int:pk>/tableau-de-bord/usage",
        views.ProjectReportUsageView.as_view(),
        name="report_usage",
    ),
    path(
        "<int:pk>/tableau-de-bord/artificialisation",
        views.ProjectReportArtifView.as_view(),
        name="report_artif",
    ),
    path(
        "<int:pk>/tableau-de-bord/groupes-communes",
        views.ProjectReportCityGroupView.as_view(),
        name="report_city_group",
    ),
    path(
        "<int:pk>/tableau-de-bord/objectif-2031",
        views.ProjectReportTarget2031View.as_view(),
        name="report_target_2031",
    ),
    # REPORT PARTIALS
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/surface",
        views.ConsoRelativeSurfaceChart.as_view(),
        name="relative-surface",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/population",
        views.ConsoRelativePopChart.as_view(),
        name="relative-pop",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/ménages",
        views.ConsoRelativeHouseholdChart.as_view(),
        name="relative-household",
    ),
    path(
        "<int:pk>/set-target-2031",
        views.SetTargetView.as_view(),
        name="set_target_2031",
    ),
    # MAP
    path("<int:pk>/map", views.ProjectMapView.as_view(), name="map"),
    path(
        "<int:pk>/carte/comprendre-mon-artificialisation",
        views.MyArtifMapView.as_view(),
        name="theme-my-artif",
    ),
    path(
        "<int:pk>/carte/consomation-villes-du-territoire",
        views.CitySpaceConsoMapView.as_view(),
        name="theme-city-conso",
    ),
    path(
        "<int:pk>/carte/artificialisation-villes-du-territoire",
        views.CityArtifMapView.as_view(),
        name="theme-city-artif",
    ),
    # DOWNLOAD
    path(
        "<int:pk>/tableau-de-bord/telechargement",
        views.ProjectReportDownloadView.as_view(),
        name="report_download",
    ),
    path(
        "<int:request_id>/word/telechargement",
        views.DownloadWordView.as_view(),
        name="word_download",
    ),
    # EXPORT
    path("exports/", views.ExportListView.as_view(), name="excel"),
    path("<int:pk>/export-excel", views.ExportExcelView.as_view(), name="export-excel"),
    # SUB APPS
    path("<int:pk>/trajectoires", include("trajectory.urls", namespace="trajectory")),
]


# Add API urls
router = routers.DefaultRouter()
router.register(r"geojson", EmpriseViewSet)
router.register(r"projects", ProjectViewSet)


urlpatterns += router.urls

project/models/project_base.py
import collections
import logging
import traceback
from decimal import Decimal
from typing import Dict, List, Literal

import pandas as pd
from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.db.models import Extent, Union
from django.contrib.gis.db.models.functions import Centroid
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Case, F, Max, Min, Q, Sum, Value, When
from django.db.models.functions import Coalesce, Concat
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from simple_history.models import HistoricalRecords

from config.storages import PublicMediaStorage
from public_data.models import (
    AdminRef,
    Cerema,
    CommuneDiff,
    CommunePop,
    CommuneSol,
    CouvertureSol,
    Departement,
    Land,
    Ocsge,
    OcsgeDiff,
    UsageSol,
)
from public_data.models.administration import Commune
from public_data.models.mixins import DataColorationMixin
from utils.db import cast_sum

from .utils import user_directory_path

logger = logging.getLogger(__name__)


class ProjectNotSaved(BaseException):
    """Exception raised when project needs to be saved once before performing the
    requested action"""

    pass


def upload_in_project_folder(project: "Project", filename: str) -> str:
    """Define where to upload project's cover image : diagnostic/<int:id>
    nb: currently you can't add cover image if project is not saved yet"""
    return f"diagnostics/{project.get_folder_name()}/{filename}"


class BaseProject(models.Model):
    class EmpriseOrigin(models.TextChoices):
        UNSET = "UNSET", "Origine non renseignée"
        FROM_SHP = "FROM_SHP", "Construit depuis un fichier shape"
        FROM_CITIES = "FROM_CITIES", "Construit depuis une liste de villes"
        WITH_EMPRISE = "WITH_EMPRISE", "Emprise déjà fournie"

    class Status(models.TextChoices):
        MISSING = "MISSING", "Emprise à renseigner"
        PENDING = "PENDING", "Traitement du fichier Shape en cours"
        SUCCESS = "SUCCESS", "Emprise renseignée"
        FAILED = "FAILED", "Création de l'emprise échouée"

    emprise_origin = models.CharField(
        "Origine de l'emprise",
        max_length=20,
        choices=EmpriseOrigin.choices,
        default=EmpriseOrigin.UNSET,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="propriétaire",
        blank=True,
        null=True,
    )
    name = models.CharField("Nom", max_length=100)
    description = models.TextField("Description", blank=True)
    shape_file = models.FileField(
        "Fichier .shp",
        upload_to=user_directory_path,
        max_length=100,
        blank=True,
        null=True,
    )
    # fields to track the shape files importation into the database
    import_error = models.TextField(
        "Message d'erreur traitement emprise",
        null=True,
        blank=True,
    )
    import_date = models.DateTimeField("Date et heure d'import", null=True, blank=True)
    import_status = models.CharField(
        "Statut import",
        max_length=10,
        choices=Status.choices,
        default=Status.MISSING,
    )

    @cached_property
    def combined_emprise(self):
        """Return a combined MultiPolygon of all emprises."""
        combined = self.emprise_set.aggregate(Union("mpoly"))
        if "mpoly__union" in combined:
            return combined["mpoly__union"]
        else:
            return None

    @cached_property
    def area(self):
        return self.combined_emprise.transform(2154, clone=True).area / 10000

    def __str__(self):
        return self.name

    def set_success(self, save=True):
        self.import_status = self.Status.SUCCESS
        self.import_date = timezone.now()
        self.import_error = None
        if save:
            self.save()

    def set_failed(self, save=True, trace=None):
        self.import_status = self.Status.FAILED
        self.import_date = timezone.now()
        if trace:
            self.import_error = trace
        else:
            self.import_error = traceback.format_exc()
        if save:
            self.save()

    class Meta:
        abstract = True


class ProjectCommune(models.Model):
    project = models.ForeignKey("project.Project", on_delete=models.CASCADE)
    commune = models.ForeignKey("public_data.Commune", on_delete=models.PROTECT)
    group_name = models.CharField("Nom du groupe", max_length=100, blank=True, null=True)


class CityGroup:
    def __init__(self, name: str):
        self.name = name
        self.cities: List[Commune] = list()

    def append(self, project_commune: ProjectCommune) -> None:
        self.cities.append(project_commune.commune)

    def __str__(self) -> str:
        return self.name


class Project(BaseProject):
    ANALYZE_YEARS = [(str(y), str(y)) for y in range(2009, 2021)]
    LEVEL_CHOICES = AdminRef.CHOICES

    is_public = models.BooleanField(
        "Est publiquement accessible",
        default=False,
        help_text=(
            "Si non coché, le diagnostic n'est accessible que par vous. Si coché "
            "tous ceux qui ont l'URL peuvent y accéder. Utile pour partager le "
            "diagnostic par e-mail à vos collègues par exemple."
        ),
    )

    analyse_start_date = models.CharField(
        "Année de début de période d'analyse",
        choices=ANALYZE_YEARS,
        default="2015",
        max_length=4,
        help_text="Utile pour analyser votre territoire sur une période différente.",
    )
    analyse_end_date = models.CharField(
        "Année de fin de période d'analyse",
        choices=ANALYZE_YEARS,
        default="2018",
        max_length=4,
        help_text="Utile pour analyser votre territoire sur une période différente.",
    )
    level = models.CharField(
        "Niveau d'analyse",
        choices=LEVEL_CHOICES,
        default="COMMUNE",
        max_length=7,
        help_text=(
            "Utilisé dans les rapports afin de déterminer le niveau "
            "d'aggrégation des données à afficher. Si "
            "EPCI est sélectionné, alors les rapports montre des données EPCI par EPCI."
        ),
    )

    @property
    def level_label(self):
        return AdminRef.get_label(self.level)

    land_type = models.CharField(
        "Type de territoire",
        choices=LEVEL_CHOICES,
        default="EPCI",
        max_length=7,
        help_text=(
            "Indique le niveau administratif des territoires sélectionnés par "
            "l'utilisateur lors de la création du diagnostic. Cela va de la commune à "
            "la région."
        ),
        blank=True,
        null=True,
    )
    land_ids = models.CharField(
        "Type de territoire",
        max_length=255,
        help_text=(
            "Contient les identifiants qui composent le territoire du diagnostic. "
            "Il faut croiser cette donnée avec 'land_type' pour être en mesure de "
            "de récupérer dans la base les instances correspondantes."
        ),
        blank=True,
        null=True,
    )
    cities = models.ManyToManyField(
        "public_data.Commune",
        verbose_name="Communes",
        through=ProjectCommune,
        blank=True,
    )
    look_a_like = models.CharField(
        "Territoire pour se comparer",
        max_length=250,
        help_text=(
            "We need a way to find Project related within Cerema's data. "
            "this is the purpose of this field which has a very specific rule of "
            "construction, it's like a slug: EPCI_[ID], DEPART_[ID] (département), "
            "REGION_[ID], COMMUNE_[ID]. "
            "field can contain several public key separate by ;"
        ),
        blank=True,
        null=True,
    )
    target_2031 = models.IntegerField(
        "Objectif 2031 (en %)",
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=50,
        help_text=(
            "A date, l'objectif national est de réduire de 50% la consommation "
            "d'espace d'ici à 2031. Cet objectif doit être personnalisé localement "
            "par les SRADDET. Vous pouvez changer l'objectif pour tester différents "
            "scénarios."
        ),
    )

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    first_year_ocsge = models.IntegerField(
        "Premier millésime OCSGE",
        validators=[MinValueValidator(2000)],
        null=True,
        blank=True,
    )

    last_year_ocsge = models.IntegerField(
        "Dernier millésime OCSGE",
        validators=[MinValueValidator(2000)],
        null=True,
        blank=True,
    )

    folder_name = models.CharField("Dossier", max_length=15, blank=True, null=True)

    territory_name = models.CharField(
        "Territoire",
        max_length=250,
        blank=True,
        null=True,
        help_text=("C'est le nom qui est utilisé pour désigner votre territoire, notamment " "dans le rapport word."),
    )

    cover_image = models.ImageField(
        upload_to=upload_in_project_folder,
        blank=True,
        null=True,
        storage=PublicMediaStorage(),
    )

    theme_map_conso = models.ImageField(
        upload_to=upload_in_project_folder,
        blank=True,
        null=True,
        storage=PublicMediaStorage(),
    )

    theme_map_artif = models.ImageField(
        upload_to=upload_in_project_folder,
        blank=True,
        null=True,
        storage=PublicMediaStorage(),
    )

    theme_map_understand_artif = models.ImageField(
        upload_to=upload_in_project_folder,
        blank=True,
        null=True,
        storage=PublicMediaStorage(),
    )

    async_city_and_combined_emprise_done = models.BooleanField(default=False)

project/models/utils.py
from django.utils import timezone


def user_directory_path(instance, filename):
    """Return a path (as a string) like user_1/202101/myfile.shp
    if instance doesn't have user property, only return end of the path"""
    today = timezone.now()
    path = f"{today.year}{today.month:02}/{filename}"
    try:
        return f"user_{instance.user.id:04}/{path}"
    except AttributeError:
        return path

project/templates/project/admin_request_detail.html
{% extends 'admin/change_form.html' %}

{% block submit_buttons_bottom %}
    {{ block.super }}
    <div class="submit-row">
        <input type="submit" value="Envoyer bilan" name="_send-action">
        <input type="submit" value="Générer bilan" name="_generate-action">
    </div>
{% endblock %}

project/templates/project/detail_menu.html
<ul class="nav nav-tabs mb-0 mt-3 justify-content-center border-bottom-0">
    <li class="nav-item pb-0">
        <a class="nav-link{% if active_page == 'synthesis' %} active bg-light{% endif %}" href="{% url 'project:report_synthesis' project.pk %}">Synthèse</a>
    </li>
    <li class="nav-item pb-0">
        <a class="nav-link{% if active_page == 'target_2031' %} active bg-light{% endif %}" href="{% url 'project:report_target_2031' project.pk %}">Objectif 2031</a>
    </li>
    <li class="nav-item pb-0">
        <a class="nav-link{% if active_page == 'consommation' %} active bg-light{% endif %}" href="{% url 'project:report_conso' project.pk %}">Consommation</a>
    </li>
    <li class="nav-item pb-0"{% if not ocsge_available %} data-toggle="tooltip" title="OCS GE n'est pas disponible pour ce territoire" aria-hidden="true"{% endif %}>
        <a class="nav-link{% if active_page == 'artificialisation' %} active bg-light{% endif %}{% if not ocsge_available %} disabled{% endif %}" href="{% url 'project:report_artif' project.pk %}">Artificialisation</a>
    </li>
    <li class="nav-item pb-0"{% if not ocsge_available %} data-toggle="tooltip" title="OCS GE n'est pas disponible pour ce territoire" aria-hidden="true"{% endif %}>
        <a class="nav-link{% if active_page == 'discover' %} active bg-light{% endif %}{% if not ocsge_available %} disabled{% endif %}" href="{% url 'project:report_couverture' project.pk %}">Découvrir l'OCSGE</a>
    </li>
    <li class="nav-item pb-0">
        <a class="nav-link{% if active_page == 'download' %} active bg-light{% endif %}" href="{% url 'project:report_download' project.pk %}">Bilan téléchargeable</a>
    </li>
</ul>

project/templates/project/form.html
{% extends 'base_connected.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block pagetitle %}
 - nouveau projet
{% endblock %}

{% block headers %}
{% endblock %}

{% block content %}
    <div class="d-flex flex-column h-100 w-100 align-items-center justify-content-center">
        <h2 class="mb-5">Nouveau projet</h2>

        <form action="{% url 'project:add' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn w-100 btn-primary mt-4" type="submit">Créer</button>
        </form>
    </div>
{% endblock %}

project/templates/project/list.html
{% extends 'index.html' %}

{% load static %}
{% load sri %}

{% block pagetitle %}
Mes diagnostics
{% endblock %}

{% block content %}
<div class="px-4">
    <div class="fr-container">
        <div class="d-flex justify-content-between align-items-center fr-mb-2w">
            <h1>Mes diagnostics</h1>
            <div class="fr-search-bar" id="header-search" role="search">
                <input class="fr-input" placeholder="Rechercher" type="search" id="filter-diagnostic-list-input">
                <button class="fr-btn" title="Rechercher"></button>
             </div>
        </div>
    </div>

    <div class="fr-container">
        <div class="fr-grid-row fr-grid-row--gutters">
            {% for project in projects %}
            <div class="fr-col-12 fr-col-md-12 diagnostic-list-item">
                <div class="fr-card fr-card--horizontal fr-card--horizontal-tier">
                    <div class="fr-card__body">
                        <div class="fr-card__content">
                            <div class="fr-card__title d-flex justify-content-between align-items-start">
                                <h3 class="diagnostic-list-item-key" data-key="{{ project.name }}">
                                    {{ project.name }}
                                </h3>
                                <a href="{% url 'project:delete' project.pk %}" class="fr-link--text-decoration-none">
                                    <button class="fr-btn fr-btn--sm fr-icon-delete-line fr-btn--tertiary-no-outline text-danger" title="Supprimer le diagnostic"></button>
                                </a>
                            </div>
                            <div class="fr-card__end">
                                <ul class="fr-tags-group">
                                    <li>
                                        <p class="fr-tag fr-tag--sm">Surface du territoire:&nbsp;<strong>{{ project.area|floatformat:0 }} ha</strong></p>
                                    </li>
                                    <li>
                                        <p class="fr-tag fr-tag--sm">Période demandée:&nbsp;<strong>De {{ project.analyse_start_date }} à {{ project.analyse_end_date }}</strong></p>
                                    </li>
                                    <li>
                                        <p class="fr-tag fr-tag--sm">Maille d'analyse:&nbsp;<strong>{{ project.level_label }}</strong></p>
                                    </li>
                                    {% if project.is_artif %}
                                    <li>
                                        <p class="fr-tag fr-tag--sm fr-tag--success"><strong>OCSGE</strong><span class="fr-icon-success-fill fr-icon--sm fr-ml-1v" aria-hidden="true"></span></p>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                        <div class="fr-card__footer">
                            <div class="d-flex">
                                <a href="{% url 'project:detail' project.id %}" class="fr-mr-2w fr-link--text-decoration-none">
                                    <button class="fr-btn fr-btn--secondary fr-btn--icon-right fr-icon-arrow-right-line">
                                        Diagnostic
                                    </button>
                                </a>

                                <a href="{% url 'project:trajectory:home' project.id %}" class="fr-link--text-decoration-none">
                                    <button class="fr-btn fr-btn--secondary fr-btn--icon-right fr-icon-arrow-right-line">
                                        Piloter sa trajectoire
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="fr-card__header">
                        <div class="fr-card__img">
                            {% if project.cover_image %}
                            <img  class="fr-responsive-img" src="{{ project.cover_image.url }}" alt="Couverture diagnostic">
                            {% else %}
                            <div class="skeleton-loader"></div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-muted">Vous n'avez aucun diagnostic.</p>
            {% endfor %}
        </div>
        <p id="diagnostic-list-empty-message" hidden>Il n'y a aucun diagnostic correspondant à votre recherche.</p>
    </div>
</div>
{% endblock %}

{% block tagging %}
<script language="javascript" nonce="{{ CSP_NONCE }}">
$( window ).on('load', function () {
    _paq.push(['trackEvent', 'Consultation diagnostic', 'Mes diagnostics'])
})
</script>
{% endblock tagging %}

project/templates/project/report_menu.html
<div class="fr-container mb-3">
    <nav class="fr-nav">
        <ul class="fr-nav__list border-bottom">
            <li class="fr-nav__item">
                <a class="fr-nav__link" {% if active_page == 'synthesis' %} aria-current="true"{% endif %} href="{% url 'project:report_synthesis' project.pk %}">Synthèse</a>
            </li>
            <li class="fr-nav__item">
                <a class="fr-nav__link" {% if active_page == 'target_2031' %} aria-current="true"{% endif %} href="{% url 'project:report_target_2031' project.pk %}">Objectif 2031</a>
            </li>
            <li class="fr-nav__item">
                <a class="fr-nav__link" {% if active_page == 'trajectory' %} aria-current="true"{% endif %} href="{% url 'project:trajectory:home' project.pk %}">Trajectoires</a>
            </li>
            <li class="fr-nav__item">
                <a class="fr-nav__link" {% if active_page == 'consommation' %} aria-current="true"{% endif %} href="{% url 'project:report_conso' project.pk %}">Consommation</a>
            </li>
            <li class="fr-nav__item"{% if not project.is_artif %} data-toggle="tooltip" title="OCS GE n'est pas disponible pour ce territoire" aria-hidden="true"{% endif %}>
                <a class="fr-nav__link {% if not project.is_artif %} disabled{% endif %}" {% if not project.is_artif %} role="link" aria-disabled="true"{% else %} href="{% url 'project:report_artif' project.pk %}"{% endif %} {% if active_page == 'artificialisation' %} aria-current="true"{% endif %}>Artificialisation</a>
            </li>
            <li class="fr-nav__item"{% if not project.is_artif %} data-toggle="tooltip" title="OCS GE n'est pas disponible pour ce territoire" aria-hidden="true"{% endif %}>
                <a class="fr-nav__link {% if not project.is_artif %} disabled{% endif %}" {% if not project.is_artif %} role="link" aria-disabled="true"{% else %} href="{% url 'project:report_discover' project.pk %}"{% endif %} {% if active_page == 'discover' %} aria-current="true"{% endif %}>Découvrir l'OCSGE</a>
            </li>
            <li class="fr-nav__item">
                <a class="fr-nav__link" {% if active_page == 'update' %}aria-current="true"{% endif %} href="{% url 'project:update' project.pk %}">Paramètres</a>
            </li>
        </ul>
    </nav>
</div>

project/templates/project/update.html
{% extends 'index.html' %}

{% load crispy_forms_tags %}
{% load static %}
{% load project_tags %}
{% load humanize %}
{% load i18n %}
{% load l10n %}
{% load sri %}

{% block pagetitle %}
Modifier
{% endblock %}

{% block headers %}
{% sri_static "project/css/project.css" %}
{% endblock %}


{% block content %}
<div class="px-4">
    {% include "project/partials/report_title.html" with title=diagnostic surface=diagnostic.area %}

    {% include "project/report_menu.html" %}

    <div class="fr-container">
        <div class="d-flex flex-column align-items-center">
            <div class="fr-col-12 fr-col-lg-8">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="d-flex fr-mt-4w">
                        <div class="flex-grow-1">
                            <a href="{% url 'project:delete' project.pk %}" class="fr-btn fr-btn--secondary text-danger">
                                Supprimer
                            </a>
                        </div>
                        <div class="fr-mr-2w">
                            <a href="{% url 'project:detail' project.pk %}" class="fr-btn fr-btn--secondary">
                                Annuler
                            </a>
                        </div>
                        <div>
                            <button class="fr-btn" type="submit">
                                Mettre à jour
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="fr-container fr-my-7w">
        <div class="fr-col-12 fr-col-lg-8 m-auto fr-pt-5w border-top">
            <div class="fw-bold" id="territoires-de-comparaison">
                <a class="float-end" href="{% url 'project:lookalike' project.id %}?next={% url 'project:update' project.id %}&anchor=territoires-de-comparaison">
                    <i class="bi bi-plus-circle"></i>
                </a>
                Territoires de comparaison
            </div>
            {% if project.look_a_like %}
                <div class="d-flex flex-column mt-2">
                {% for land in project.get_look_a_like %}
                    <div class="w100">
                        {{ land.name }}
                        <a href="{% url 'project:rm-lookalike' project.id land.public_key %}?next={% url 'project:update' project.id %}&anchor=territoires-de-comparaison" class="float-end"><i class="bi bi-trash text-danger"></i></a>
                    </div>
                {% endfor %}
                </div>
            {% else %}
            <p class="text-muted">Aucun territoire.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block bodyend %}
<script language="javascript" nonce="{{ CSP_NONCE }}">
const queryString = window.location.search
const urlParams = new URLSearchParams(queryString)
const next = urlParams.get('next')
if (next == "report-target-2031"){
    $('#id_target_2031').focus()
}
</script>
{% endblock bodyend %}

{% block tagging %}
<script language="javascript" nonce="{{ CSP_NONCE }}">
$( window ).on('load', function () {
    _paq.push(['trackEvent', 'Consultation diagnostic', 'Tableau de bord', 'Synthèse'])
})

var fired = false
$( window ).scroll(function() {
    if(fired == false && $( window ).scrollTop() + $( window ).height() > $( "#block-content" ).height() - 100) {
        _paq.push(['trackEvent', 'Consultation diagnostic', 'Fin tableau de bord', 'Synthèse'])
        fired = true
    }
})
</script>
{% endblock tagging %}