config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    """Snippet to test Sentry integration"""
    division_by_zero = 1 / 0  # # noqa: F841


admin.site.site_header = f"SPARTE administration v{settings.OFFICIAL_VERSION}"


urlpatterns = [
    path("boom/", trigger_error),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("public/", include("public_data.urls")),
    path("project/", include("project.urls")),
    path("carte/", include("carto.urls")),
    path("word/", include("diagnostic_word.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    try:
        # try except required to activate debug in staging server
        # where we do not install dev dependencies
        import debug_toolbar  # noqa: E402

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

    path = settings.BASE_DIR / "htmlcov"
    urlpatterns += static("/cov/", document_root=path)

home/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .api.views import RegionViewSet

app_name = "home"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("mentions-legales", views.LegalNoticeView.as_view(), name="cgv"),
    path("confidentialité", views.PrivacyView.as_view(), name="privacy"),
    path("stats", views.StatsView.as_view(), name="stats"),
    path("test", views.TestView.as_view(), name="test"),
    path("accessibilite", views.AccessView.as_view(), name="accessibilite"),
    path("robots.txt", views.RobotView.as_view(), name="robots"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path(
        "newsletter/inscription",
        views.NewsletterSubscriptionView.as_view(),
        name="nwl-subscription",
    ),
    path(
        "newsletter/confirmation/<slug:token>",
        views.NewsLetterConfirmationView.as_view(),
        name="nwl-confirmation",
    ),
    path(
        "emails",
        views.AllEmailsView.as_view(),
        name="all-emails",
    ),
]

router = routers.DefaultRouter()
router.register(r"stats/region", RegionViewSet)
urlpatterns += router.urls

project/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views
from .api_views import EmpriseViewSet, ProjectViewSet

app_name = "project"


# See below for DRF's router inclusions

urlpatterns = [
    # ### PROJECTS ###
    # CREATE
    path("nouveau", views.CreateProjectViews.as_view(), name="create"),
    path("<int:pk>/en-construction", views.SplashScreenView.as_view(), name="splash"),
    path(
        "<int:pk>/en-construction/progress",
        views.SplashProgressionView.as_view(),
        name="splash-progress",
    ),
    # CRUD
    path("", views.ProjectListView.as_view(), name="list"),
    path("<int:pk>/", views.ProjectReportSynthesisView.as_view(), name="detail"),
    path("<int:pk>/ajouter", views.ClaimProjectView.as_view(), name="claim"),
    path("<int:pk>/edit", views.ProjectUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="delete"),
    path("<int:pk>/ajouter-voisin", views.ProjectAddLookALike.as_view(), name="lookalike"),
    path(
        "<int:pk>/retirer-voisin/<slug:public_key>",
        views.ProjectRemoveLookALike.as_view(),
        name="rm-lookalike",
    ),
    # REPORT
    path(
        "<int:pk>/tableau-de-bord/consommation",
        views.ProjectReportConsoView.as_view(),
        name="report_conso",
    ),
    path(
        "<int:pk>/tableau-de-bord/synthesis",
        views.ProjectReportSynthesisView.as_view(),
        name="report_synthesis",
    ),
    path(
        "<int:pk>/tableau-de-bord/découvrir-l-ocsge",
        views.ProjectReportDicoverOcsgeView.as_view(),
        name="report_discover",
    ),
    path(
        "<int:pk>/tableau-de-bord/usage",
        views.ProjectReportUsageView.as_view(),
        name="report_usage",
    ),
    path(
        "<int:pk>/tableau-de-bord/artificialisation",
        views.ProjectReportArtifView.as_view(),
        name="report_artif",
    ),
    path(
        "<int:pk>/tableau-de-bord/groupes-communes",
        views.ProjectReportCityGroupView.as_view(),
        name="report_city_group",
    ),
    path(
        "<int:pk>/tableau-de-bord/objectif-2031",
        views.ProjectReportTarget2031View.as_view(),
        name="report_target_2031",
    ),
    # REPORT PARTIALS
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/surface",
        views.ConsoRelativeSurfaceChart.as_view(),
        name="relative-surface",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/population",
        views.ConsoRelativePopChart.as_view(),
        name="relative-pop",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/ménages",
        views.ConsoRelativeHouseholdChart.as_view(),
        name="relative-household",
    ),
    path(
        "<int:pk>/set-target-2031",
        views.SetTargetView.as_view(),
        name="set_target_2031",
    ),
    # MAP
    path("<int:pk>/map", views.ProjectMapView.as_view(), name="map"),
    path(
        "<int:pk>/carte/comprendre-mon-artificialisation",
        views.MyArtifMapView.as_view(),
        name="theme-my-artif",
    ),
    path(
        "<int:pk>/carte/consomation-villes-du-territoire",
        views.CitySpaceConsoMapView.as_view(),
        name="theme-city-conso",
    ),
    path(
        "<int:pk>/carte/artificialisation-villes-du-territoire",
        views.CityArtifMapView.as_view(),
        name="theme-city-artif",
    ),
    # DOWNLOAD
    path(
        "<int:pk>/tableau-de-bord/telechargement",
        views.ProjectReportDownloadView.as_view(),
        name="report_download",
    ),
    path(
        "<int:request_id>/word/telechargement",
        views.DownloadWordView.as_view(),
        name="word_download",
    ),
    # EXPORT
    path("exports/", views.ExportListView.as_view(), name="excel"),
    path("<int:pk>/export-excel", views.ExportExcelView.as_view(), name="export-excel"),
    # SUB APPS
    path("<int:pk>/trajectoires", include("trajectory.urls", namespace="trajectory")),
]


# Add API urls
router = routers.DefaultRouter()
router.register(r"geojson", EmpriseViewSet)
router.register(r"projects", ProjectViewSet)


urlpatterns += router.urls

project/models/create.py
""" Contains all logic to create a project """
from typing import List

import celery

from public_data.models import AdminRef, Land
from users.models import User

from .project_base import Project


def create_from_public_key(
    public_key: str,
    start: str = "2011",
    end: str = "2020",
    user: User | None = None,
) -> Project:
    """Create a project from one only public_key"""
    from project import tasks as t

    land = Land(public_key)
    level = AdminRef.get_analysis_default_level(public_key.split("_")[0])
    project = Project(
        name=f"Diagnostic de {land.name}",
        is_public=True,
        analyse_start_date=start,
        analyse_end_date=end,
        level=level,
        land_ids=str(land.id),
        land_type=land.land_type,
        territory_name=land.name,
        user=user if user and user.is_authenticated else None,
    )
    project._change_reason = "create_from_public_key"
    project.set_success(save=True)

    # use celery to speedup user experience
    celery.chain(
        t.add_city_and_set_combined_emprise.si(project.id, public_key),
        celery.group(
            t.find_first_and_last_ocsge.si(project.id),
            t.add_neighboors.si(project.id),
        ),
        celery.group(
            t.generate_cover_image.si(project.id),
            t.generate_theme_map_conso.si(project.id),
            t.generate_theme_map_artif.si(project.id),
            t.generate_theme_map_understand_artif.si(project.id),
        ),
    ).apply_async()

    return project


def create_from_public_key_list(
    public_key_list: List[str],
    start: str = "2011",
    end: str = "2020",
    user: User | None = None,
) -> Project:
    """Create a project from a list of public_keys"""

    raise NotImplementedError("TODO update code when used")  # NOSONAR

    from project import tasks as t

    # if there is on ly one public_key, use the dedicated function
    if len(public_key_list) == 1:
        return create_from_public_key(public_key_list[0], start=start, end=end, user=user)

    lands = Land.get_lands(public_key_list)
    land_type = AdminRef.get_admin_level({p.split("_")[0] for p in public_key_list})

    project = Project(
        name="Diagnostic de plusieurs communes",
        is_public=True,
        analyse_start_date=start,
        analyse_end_date=end,
        level=AdminRef.get_analysis_default_level(land_type),
        land_ids=",".join(str(_.id) for _ in lands),
        land_type=land_type,
        territory_name="territoire composite",
        user=user,
    )
    project.set_success(save=True)

    # use celery to speedup user experience
    jobs = [
        t.generate_cover_image.si(project.id),
        t.find_first_and_last_ocsge.si(project.id),
    ]
    if project.land_type != AdminRef.COMPOSITE:
        # insert in jobs list before cover generation
        jobs.append(t.add_neighboors.si(project.id))

    celery.chain(
        t.add_city_and_set_combined_emprise.si(project.id, "-".join(public_key_list)),
        celery.group(jobs),
    ).apply_async()

    return project

project/models/utils.py
from django.utils import timezone


def user_directory_path(instance, filename):
    """Return a path (as a string) like user_1/202101/myfile.shp
    if instance doesn't have user property, only return end of the path"""
    today = timezone.now()
    path = f"{today.year}{today.month:02}/{filename}"
    try:
        return f"user_{instance.user.id:04}/{path}"
    except AttributeError:
        return path

project/forms.py
from django import forms

from project.models import Project
from public_data.models import AdminRef, Departement, Epci, Region


class KeywordForm(forms.Form):
    keyword = forms.CharField(label="Mot clé")


class SelectTerritoryForm(forms.Form):
    keyword = forms.CharField(label="Mot clé")
    selection = forms.CharField(required=False)
    region = forms.ModelChoiceField(queryset=Region.objects.all().order_by("name"), required=False)
    departement = forms.ModelChoiceField(queryset=Departement.objects.all().order_by("name"), required=False)
    epci = forms.ModelChoiceField(queryset=Epci.objects.all().order_by("name"), required=False)
    search_region = forms.BooleanField(required=False, initial=True)
    search_departement = forms.BooleanField(required=False, initial=True)
    search_scot = forms.BooleanField(required=False, initial=True)
    search_epci = forms.BooleanField(required=False, initial=True)
    search_commune = forms.BooleanField(required=False, initial=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["region"].widget.attrs.update({"class": "adv-item"})
        self.fields["departement"].widget.attrs.update({"class": "adv-item"})
        self.fields["epci"].widget.attrs.update({"class": "adv-item"})

        if "region" in self.data and self.data["region"]:
            try:
                region = Region.objects.get(pk=int(self.data["region"]))
                dept_qs = Departement.objects.filter(region=region).order_by("name")
                self.fields["departement"].queryset = dept_qs
            except Region.DoesNotExist:
                pass
        if "departement" in self.data and self.data["departement"]:
            try:
                dept = Departement.objects.get(pk=int(self.data["departement"]))
                epci_qs = Epci.objects.filter(departements=dept).order_by("name")
                self.fields["epci"].queryset = epci_qs
            except Departement.DoesNotExist:
                pass


class UpdateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "territory_name",
            "analyse_start_date",
            "analyse_end_date",
            "level",
            "target_2031",
            "is_public",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.land_type:
            choices = AdminRef.get_available_analysis_level(self.instance.land_type)
            self.fields["level"].choices = [(c, AdminRef.get_label(c)) for c in choices]

    def save(self, *args, **kwargs):
        self.instance._change_reason = "update_project"
        return super().save(*args, **kwargs)

project/views/api.py
from django.contrib.gis.geos import Polygon
from django.db.models import F, OuterRef, Subquery
from django.http import JsonResponse
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework_gis import filters

from project.mixins import UserQuerysetOrPublicMixin
from project.models import Project
from project.serializers import ProjectCommuneSerializer
from public_data.models import Cerema, Commune


class ProjectViewSet(UserQuerysetOrPublicMixin, viewsets.ReadOnlyModelViewSet):
    bbox_filter_field = "mpoly"
    bbox_filter_include_overlapping = True
    filter_backends = (filters.InBBoxFilter,)
    queryset = Project.objects.all()
    serializer_class = ProjectCommuneSerializer

    @action(detail=True, methods=["get"])
    def communes(self, request):
        project = self.get_object()
        sum_function = sum([F(f) for f in Cerema.get_art_field(project.analyse_start_date, project.analyse_end_date)])
        qs = Cerema.objects.annotate(artif_area=sum_function)
        queryset = Commune.objects.annotate(
            artif_area=Subquery(qs.filter(city_insee=OuterRef("insee")).values("artif_area")[:1])
        )
        bbox = self.request.GET.get("bbox", None)
        if bbox is not None and len(bbox) > 0:
            polygon_box = Polygon.from_bbox(bbox.split(","))
            queryset = queryset.filter(mpoly__within=polygon_box)
        serializer = ProjectCommuneSerializer(queryset, many=True)
        return JsonResponse(serializer.data, status=200)

project/views/mixins.py
"""Mixins available for all views."""
from django.db.models import Q
from django.urls import reverse_lazy

from utils.views_mixins import BreadCrumbMixin, GetObjectMixin


class UserQuerysetOnlyMixin:
    """Filter queryset to return only connected user objects."""

    def get_queryset(self):
        # get queryset from class queryset var
        qs = super().get_queryset()
        # apply filter on user owned project only
        user = self.request.user
        if user.is_authenticated:
            return qs.filter(user=user)
        return qs.none()


class UserQuerysetOrPublicMixin:
    """Filter project to return all user's project or public ones."""

    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user.is_authenticated:
            return qs.filter(Q(user=user) | Q(is_public=True))
        else:
            return qs.filter(is_public=True)


class GroupMixin(GetObjectMixin, UserQuerysetOrPublicMixin, BreadCrumbMixin):
    """Simple trick to not repeat myself. Pertinence to be evaluated."""

    context_object_name = "project"

    def get_context_breadcrumbs(self):
        breadcrumbs = super().get_context_breadcrumbs()
        breadcrumbs.append(
            {"href": reverse_lazy("project:list"), "title": "Mes diagnostics"},
        )
        try:
            project = self.get_object()
            breadcrumbs.append(
                {
                    "href": reverse_lazy("project:detail", kwargs={"pk": project.id}),
                    "title": project.name,
                }
            )
        except AttributeError:
            pass
        return breadcrumbs

project/templates/project/partials/household_comparison_conso.html
{% load highcharts_tags %}

<h3>Consommation d'espaces par ménages</h3>

<p>Mise en perspective de la consommation d'espaces avec les données de l'INSEE.</p>

<div class="border fr-p-2w">
    {% display_chart_test 'household_chart' household_chart CSP_NONCE %}
</div>


<div class="fr-callout bg-white fr-p-2w mt-4">
    <button class="fr-btn fr-btn--secondary fr-btn--sm fr-btn--icon-right fr-icon-arrow-down-s-fill mt-0" aria-expanded="false" aria-controls="target-data-5">Données</button>
    <div class="fr-collapse" id="target-data-5">
        <h6 class="fr-mt-2w">Source</h6>
        <p>Ménages INSEE, sur la période d'analyse (millésimes 2008-2013-2018) : <a href="https://www.insee.fr/fr/statistiques/5395819?sommaire=5395886" target="_blank" rel="noreferrer noopener">Couples-Familles-Ménages en 2018</a> (colonnes C18_MEN, C13_MEN et C08_MEN)</p>

        <h6 class="fr-mt-2w">Calcul</h6>
        <p>Les données pour les années manquantes sont obtenues par approximation affine, les décalages liés aux arrondis sont lissés.</p>

        <h6 class="fr-mt-2w">Données</h6>
        <table class="table table-striped table-sm table-borderless">
            <thead>
                <tr>
                    <th scope="col">{{ col_name }}</th>
                    {% for year in project.years %}
                    <th scope="col" class="text-end">{{ year }}</th>
                    {% endfor %}
                    <th scope="col" class="text-end">Total</th>
                </tr>
            </thead>
            <tbody>
                {% for city_name, data in household_table.items %}
                <tr>
                    <th scope="row">{{ city_name }}</th>
                    {% for year, val in data.items %}
                    <td align="right">{{ val|floatformat:0 }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="border fr-p-2w">
    <div class="d-flex justify-content-end align-items-center fr-mb-2w">
        <div class="dropdown custom-dropdown fr-mr-2w" data-toggle="tooltip" title="Exporter le graphique">
            <button class="fr-btn fr-icon-download-line fr-btn--tertiary fr-btn--sm" data-bs-toggle="dropdown" aria-expanded="false"></button>

            <ul class="dropdown-menu">
                <li>
                    <a class="fr-nav__link export-chart" href="#" data-chart-target="conso_household_chart" data-type="image/png">PNG</a>
                </li>
                <li>
                    <a class="fr-nav__link export-chart" href="#" data-chart-target="conso_household_chart" data-type="image/jpeg">JPEG</a>
                </li>
                <li>
                    <a class="fr-nav__link export-chart" href="#" data-chart-target="conso_household_chart" data-type="application/pdf">PDF</a>
                </li>
                <li>
                    <a class="fr-nav__link export-chart" href="#" data-chart-target="conso_household_chart" data-type="image/svg+xml">Vectoriel</a>
                </li>
            </ul>
        </div>

        <button class="fr-btn fr-icon-drag-move-2-line fr-btn--tertiary fr-btn--sm fr-mr-2w fullscreen-chart" data-chart-target="conso_household_chart" data-toggle="tooltip" title="Afficher le graphique en plein écran"></button>

        <button class="fr-btn fr-icon-question-line fr-btn--tertiary fr-btn--sm" data-bs-toggle="modal" data-bs-target="#menage-astuce" data-toggle="tooltip" title="Astuces pour lire le graphique" aria-hidden="true"></button>
    </div>
    <div id="conso_household_chart"></div>
</div>
{% display_chart 'conso_household_chart' conso_household_chart CSP_NONCE %}

<div class="fr-callout bg-white fr-p-2w mt-4">
    <button class="fr-btn fr-btn--secondary fr-btn--sm fr-btn--icon-right fr-icon-arrow-down-s-fill mt-0" aria-expanded="false" aria-controls="target-data-6">Données</button>
    <div class="fr-collapse" id="target-data-6">
        <h6 class="fr-mt-2w">Sourcce</h6>
        <ul>
            <li>Ménages INSEE, sur la période d'analyse (millésimes 2008-2013-2018) : <a href="https://www.insee.fr/fr/statistiques/5395819?sommaire=5395886" target="_blank" rel="noreferrer noopener">Couples-Familles-Ménages en 2018</a> (colonnes C18_MEN, C13_MEN et C08_MEN)</li>
            <li>Données d'évolution des fichiers fonciers du Cérema issus des données MAJIC (Mise A Jour de l'Information Cadastrale) de la DGFIP, sur la période d'analyse (millésime min : 2009, millésime max : 2021)</li>
        </ul>

        <h6 class="fr-mt-2w">Calcul</h6>
        <p>Consommation d'espaces NAF annuelle divisée par l'évolution des ménages, par maille d'analyse du territoire de diagnostic.</p>

        <h6 class="fr-mt-2w">Données</h6>
        <table class="table table-striped table-sm table-borderless">
            <thead>
                <tr>
                    <th scope="col" class="text-end">(en Hectares par ménage)</th>
                    {% for year in project.years %}
                    <th scope="col" class="text-end">{{ year }}</th>
                    {% endfor %}
                    <th scope="col" class="text-end">Total</th>
                </tr>
            </thead>
            <tbody>
                {% for city_name, data in conso_household_table.items %}
                <tr>
                    <th scope="row">{{ city_name }}</th>
                    {% for year, val in data.items %}
                    <td align="right">{{ val|floatformat:2 }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="menage-astuce" tabindex="-1" aria-labelledby="menage-astuce-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="fr-modal__body">
            <div class="fr-modal__header">
                <button class="fr-link--close fr-link" data-bs-dismiss="modal" aria-label="Close">Fermer</button>
            </div>
            <div class="fr-modal__content">
                <h1 id="fr-modal-2-title" class="fr-modal__title" id="menage-astuce-label">
                    <span class="fr-fi-arrow-right-line fr-fi--lg"></span>
                    Astuces - Consommation d'espaces par ménages
                </h1>
                <p>L'évolution des ménages permet d'analyser plus finement la dynamique du territoire, plus révélatrice des tendances en besoin d'urbanisation.</p>
            </div>
        </div>
    </div>
</div>

project/templates/project/partials/report_set_target_2031.html
{% load crispy_forms_tags %}

{% if success_message %}
    {% load highcharts_tags %}

    <div class="fade-in fr-alert fr-alert--success fr-alert--sm" role="alert">
        <h3 class="fr-alert__title">Votre objectif a été mis à jour.</h3>
    </div>

    <div id="objective-chart-swapper" hx-swap-oob="true">
        <div id="objective_chart"></div>
        {% display_chart 'objective_chart' objective_chart CSP_NONCE %}
    </div>

    <div id="alert-swapper" hx-swap-oob="true">
        {% if project.target_2031 != 50 %}
            <div class="fr-alert fr-alert--info fr-alert--sm mt-3">
                <p>Vous avez personnalisé l'objectif de votre territoire à {{ project.target_2031 }}%.</p>
            </div>
        {% endif %}
    </div>
    
    <span id="button-swapper" hx-swap-oob="true">{{ project.target_2031 }}</span>
    <span id="objective-conso-swapper" hx-swap-oob="true">{{ objective_chart.conso_2031|floatformat:1 }}</span>
    <span id="objective-annual-swapper" hx-swap-oob="true">{{ objective_chart.annual_objective_2031|floatformat:1 }}</span>
{% else %}
    <form hx-post="{% url 'project:set_target_2031' project.pk %}">
        {% csrf_token %}
        {{ form|crispy }}
        <ul class="fr-btns-group fr-btns-group--right fr-btns-group--inline-lg fr-mt-2w">
            <li>
                <button id="dl_btn" class="fr-btn" type="submit">
                    Enregistrer
                </button>
            </li>
        </ul>
    </form>
{% endif %}

project/templates/project/partials/report_title.html
<div class="fr-container">
    <div class="d-flex justify-content-between">
        <div>
            <h1 class="mb-3">{{ title }}</h1>
            <ul class="fr-tags-group">
                <li>
                    <p class="fr-tag fr-tag--sm">Surface du territoire:&nbsp;<strong>{{ surface|floatformat:0 }} ha</strong></p>
                </li>
                <li>
                    <p class="fr-tag fr-tag--sm">Période demandée:&nbsp;<strong>De {{ project.analyse_start_date }} à {{ project.analyse_end_date }}</strong></p>
                </li>
                <li>
                    <p class="fr-tag fr-tag--sm">Maille d'analyse:&nbsp;<strong>{{ project.level_label }}</strong></p>
                </li>
            </ul>
        </div>

        <div class="dropdown custom-dropdown mt-2">
            <button class="fr-btn" data-bs-toggle="dropdown" aria-expanded="false">
                Télécharger mon diagnostic
            </button>

            <ul class="dropdown-menu w-100">
                <li>
                    <a class="fr-nav__link" hx-get="{% url 'project:report_download' project.pk %}" hx-target="#fr-modal__form" href="#" id="fr-modal-download-word" data-fr-opened="false" aria-controls="fr-modal-download-word">
                        Word
                    </a>
                </li>
                <li>
                    <a class="fr-nav__link" href="{% url 'project:export-excel' project.pk %}">
                        Excel
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<dialog aria-labelledby="fr-modal-2-title" id="fr-modal-download-word" class="fr-modal" role="dialog" >
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" aria-controls="fr-modal-download-word">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-2-title" class="fr-modal__title">
                            Recevoir le diagnostic par e-mail
                        </h1>
                        <div id="fr-modal__form"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

<script language="javascript" nonce="{{ CSP_NONCE }}">
    document.getElementById("fr-modal-download-word").onclick = () => {
        document.getElementById("fr-modal__form").innerHTML = "<div class='fr-custom-loader'></div>";
    }
</script>