config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    """Snippet to test Sentry integration"""
    division_by_zero = 1 / 0  # # noqa: F841


admin.site.site_header = f"SPARTE administration v{settings.OFFICIAL_VERSION}"


urlpatterns = [
    path("boom/", trigger_error),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("public/", include("public_data.urls")),
    path("project/", include("project.urls")),
    path("carte/", include("carto.urls")),
    path("word/", include("diagnostic_word.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    try:
        # try except required to activate debug in staging server
        # where we do not install dev dependencies
        import debug_toolbar  # noqa: E402

        urlpatterns += [
            path("__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

    path = settings.BASE_DIR / "htmlcov"
    urlpatterns += static("/cov/", document_root=path)

home/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .api.views import RegionViewSet

app_name = "home"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("mentions-legales", views.LegalNoticeView.as_view(), name="cgv"),
    path("confidentialité", views.PrivacyView.as_view(), name="privacy"),
    path("stats", views.StatsView.as_view(), name="stats"),
    path("test", views.TestView.as_view(), name="test"),
    path("accessibilite", views.AccessView.as_view(), name="accessibilite"),
    path("robots.txt", views.RobotView.as_view(), name="robots"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path(
        "newsletter/inscription",
        views.NewsletterSubscriptionView.as_view(),
        name="nwl-subscription",
    ),
    path(
        "newsletter/confirmation/<slug:token>",
        views.NewsLetterConfirmationView.as_view(),
        name="nwl-confirmation",
    ),
    path(
        "emails",
        views.AllEmailsView.as_view(),
        name="all-emails",
    ),
]

router = routers.DefaultRouter()
router.register(r"stats/region", RegionViewSet)
urlpatterns += router.urls

project/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views
from .api_views import EmpriseViewSet, ProjectViewSet

app_name = "project"


# See below for DRF's router inclusions

urlpatterns = [
    # ### PROJECTS ###
    # CREATE
    path("nouveau", views.CreateProjectViews.as_view(), name="create"),
    path("<int:pk>/en-construction", views.SplashScreenView.as_view(), name="splash"),
    path(
        "<int:pk>/en-construction/progress",
        views.SplashProgressionView.as_view(),
        name="splash-progress",
    ),
    # CRUD
    path("", views.ProjectListView.as_view(), name="list"),
    path("<int:pk>/", views.ProjectReportSynthesisView.as_view(), name="detail"),
    path("<int:pk>/ajouter", views.ClaimProjectView.as_view(), name="claim"),
    path("<int:pk>/edit", views.ProjectUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="delete"),
    path("<int:pk>/ajouter-voisin", views.ProjectAddLookALike.as_view(), name="lookalike"),
    path(
        "<int:pk>/retirer-voisin/<slug:public_key>",
        views.ProjectRemoveLookALike.as_view(),
        name="rm-lookalike",
    ),
    # REPORT
    path(
        "<int:pk>/tableau-de-bord/consommation",
        views.ProjectReportConsoView.as_view(),
        name="report_conso",
    ),
    path(
        "<int:pk>/tableau-de-bord/synthesis",
        views.ProjectReportSynthesisView.as_view(),
        name="report_synthesis",
    ),
    path(
        "<int:pk>/tableau-de-bord/découvrir-l-ocsge",
        views.ProjectReportDicoverOcsgeView.as_view(),
        name="report_discover",
    ),
    path(
        "<int:pk>/tableau-de-bord/usage",
        views.ProjectReportUsageView.as_view(),
        name="report_usage",
    ),
    path(
        "<int:pk>/tableau-de-bord/artificialisation",
        views.ProjectReportArtifView.as_view(),
        name="report_artif",
    ),
    path(
        "<int:pk>/tableau-de-bord/groupes-communes",
        views.ProjectReportCityGroupView.as_view(),
        name="report_city_group",
    ),
    path(
        "<int:pk>/tableau-de-bord/objectif-2031",
        views.ProjectReportTarget2031View.as_view(),
        name="report_target_2031",
    ),
    # REPORT PARTIALS
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/surface",
        views.ConsoRelativeSurfaceChart.as_view(),
        name="relative-surface",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/population",
        views.ConsoRelativePopChart.as_view(),
        name="relative-pop",
    ),
    path(
        "<int:pk>/tableau-de-bord/consommation-relative/ménages",
        views.ConsoRelativeHouseholdChart.as_view(),
        name="relative-household",
    ),
    path(
        "<int:pk>/set-target-2031",
        views.SetTargetView.as_view(),
        name="set_target_2031",
    ),
    # MAP
    path("<int:pk>/map", views.ProjectMapView.as_view(), name="map"),
    path(
        "<int:pk>/carte/comprendre-mon-artificialisation",
        views.MyArtifMapView.as_view(),
        name="theme-my-artif",
    ),
    path(
        "<int:pk>/carte/consomation-villes-du-territoire",
        views.CitySpaceConsoMapView.as_view(),
        name="theme-city-conso",
    ),
    path(
        "<int:pk>/carte/artificialisation-villes-du-territoire",
        views.CityArtifMapView.as_view(),
        name="theme-city-artif",
    ),
    # DOWNLOAD
    path(
        "<int:pk>/tableau-de-bord/telechargement",
        views.ProjectReportDownloadView.as_view(),
        name="report_download",
    ),
    path(
        "<int:request_id>/word/telechargement",
        views.DownloadWordView.as_view(),
        name="word_download",
    ),
    # EXPORT
    path("exports/", views.ExportListView.as_view(), name="excel"),
    path("<int:pk>/export-excel", views.ExportExcelView.as_view(), name="export-excel"),
    # SUB APPS
    path("<int:pk>/trajectoires", include("trajectory.urls", namespace="trajectory")),
]


# Add API urls
router = routers.DefaultRouter()
router.register(r"geojson", EmpriseViewSet)
router.register(r"projects", ProjectViewSet)


urlpatterns += router.urls

public_data/urls.py
from django.urls import path
from rest_framework import routers

from .api.views import (
    ArtificialAreaViewSet,
    CommuneViewSet,
    CouvertureSolViewset,
    DepartementViewSet,
    EpciViewSet,
    OcsgeDiffViewSet,
    OcsgeViewSet,
    RegionViewSet,
    UsageSolViewset,
    ZoneConstruiteViewSet,
)
from .views import DisplayMatrix

app_name = "public_data"


urlpatterns = [
    path("matrix", DisplayMatrix.as_view(), name="matrix"),
]


router = routers.DefaultRouter()
router.register(r"communes", CommuneViewSet)
router.register(r"referentiel/couverture-sol", CouvertureSolViewset)
router.register(r"referentiel/usage-sol", UsageSolViewset)
router.register(r"ocsge/general", OcsgeViewSet)
router.register(r"ocsge/diff", OcsgeDiffViewSet)
router.register(r"ocsge/zones-construites", ZoneConstruiteViewSet)
router.register(r"ocsge/zones-artificielles", ArtificialAreaViewSet)
router.register(r"referentiel/region", RegionViewSet)
router.register(r"referentiel/departement", DepartementViewSet)
router.register(r"referentiel/epci", EpciViewSet)

urlpatterns += router.urls

users/urls.py
from django.conf import settings
from django.urls import path
from django.urls import reverse_lazy

from . import views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "users"

urlpatterns = [
    path("signup/", views.UserCreateView.as_view(), name="signup"),
    path("signout/", views.SignoutView.as_view(), name="signout"),
    path("signin/", views.SigninView.as_view(), name="signin"),
    path("profile/", views.ProfilFormView.as_view(), name="profile"),
    path("password/", views.UpdatePwFormView.as_view(), name="password"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            email_template_name="users/password_reset_email.txt",
            html_email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
            extra_email_context={"DOMAIN_URL": settings.DOMAIN_URL.strip("/")},
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("unsubscribe/", views.UserDeleteView.as_view(), name="unsubscribe"),
]

templates/footer.html
<footer role="contentinfo" class="fr-footer fr-mt-5w" id="footer">
  <div class="fr-container">
    <div class="fr-footer__body">
      <div class="fr-footer__brand fr-enlarge-link">
        <a href="/" title="Retour à l’accueil">
          {% block brand %}
            <p class="fr-logo" title="{{ SITE_CONFIG.footer_brand|default:'république française' }}">
              {{ SITE_CONFIG.footer_brand_html| default_if_none:'république<br />française' | safe }}
            </p>
          {% endblock brand %}
        </a>
      </div>
      <div class="fr-footer__content">
        <p class="fr-footer__content-desc">
          {% block footer_content %}
            {{ SITE_CONFIG.footer_description | safe }}
            <br><br>
            Le code source est ouvert et les contributions sont bienvenues.
            <a href="https://github.com/MTES-MCT/sparte" target="_blank" rel="noopener" title="Voir le code source - nouvelle fenêtre">Voir le code source</a>
          {% endblock footer_content %}</p>
        <ul class="fr-footer__content-list">
          <li class="fr-footer__content-item">
            <a class="fr-footer__content-link" href="https://legifrance.gouv.fr">legifrance.gouv.fr</a>
          </li>
          <li class="fr-footer__content-item">
            <a class="fr-footer__content-link" href="https://gouvernement.fr">gouvernement.fr</a>
          </li>
          <li class="fr-footer__content-item">
            <a class="fr-footer__content-link" href="https://service-public.fr">service-public.fr</a>
          </li>
          <li class="fr-footer__content-item">
            <a class="fr-footer__content-link" href="https://data.gouv.fr">data.gouv.fr</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="fr-footer__bottom">
      <ul class="fr-footer__bottom-list">
        {% block footer_links %}
          <li class="fr-footer__bottom-item">
            <a class="fr-footer__bottom-link" href="{% url 'home:accessibilite' %}">Accessibilité: {{ SITE_CONFIG.get_accessibility_status_display|default:'non' }} conforme</a>
          </li>
          <li class="fr-footer__bottom-item">
            <a class="fr-footer__bottom-link" href="{% url 'home:cgv' %}">Mentions légales</a>
          </li>
          <li class="fr-footer__bottom-item">
            <a class="fr-footer__bottom-link" href="{% url 'home:privacy' %}">Données personnelles</a>
          </li>
          <li class="fr-footer__bottom-item">
            <a class="fr-footer__bottom-link" href="{% url 'home:stats' %}">Statistiques</a>
          </li>
          <li class="fr-footer__bottom-item">
            <a class="fr-footer__bottom-link" href="{{ EXTERNAL_DOC }}" target="_blank" title="Consulter la documentation - nouvelle fenêtre" rel="noopener">Documentations</a>
          </li>
          <li class="fr-footer__bottom-item">
            <a class="fr-footer__bottom-link" href="{% url 'home:contact' %}">Contactez-nous</a>
          </li>
        {% endblock footer_links %}
      </ul>
      <div class="fr-footer__bottom-copy">
        <p>
          Sauf mention contraire, tous les textes de ce site sont sous <a href="https://github.com/etalab/licence-ouverte/blob/master/LO.md" target="_blank" rel="noopener noreferrer">licence etalab-2.0</a>
        </p>
      </div>
    </div>
  </div>
</footer>

templates/header.html
<header role="banner" class="fr-header">
    <div class="fr-header__body">
        <div class="fr-container">
            <div class="fr-header__body-row position-relative">
                <div class="fr-header__brand fr-enlarge-link">
                    <div class="fr-header__brand-top">
                        <div class="fr-header__logo">
                            <p class="fr-logo">
                                République
                                <br>Française
                            </p>
                        </div>
                        <div class="fr-header__navbar">
                            <button class="fr-btn--menu fr-btn" data-fr-opened="false" aria-controls="modal-499" aria-haspopup="menu" id="button-500" title="Menu">
                                Menu
                            </button>
                        </div>
                    </div>
                    <div class="fr-header__service">
                        <a href="/" title="Accueil - [À MODIFIER - Nom du site / service] - Nom de l’entité (ministère, secrétariat d‘état, gouvernement)">
                            <p class="fr-header__service-title">
                                SPARTE
                                <sup class="fr-badge fr-badge--sm fr-badge--blue-cumulus">Beta</sup>
                            </p>
                        </a>
                        <small class="fr-header__service-tagline">Mesurer votre consommation d'espaces et l'artificialisation de votre territoire</small>
                    </div>
                </div>
                <div class="fr-header__tools">
                    <div class="fr-header__tools-links">
                        <ul class="fr-btns-group">
                            <li>
                                <a class="fr-btn" href="{% url 'project:create' %}">
                                    Créer un diagnostic
                                </a>
                            </li>
                            {% if user.is_authenticated %}
                            <li>
                                <button class="fr-btn" aria-expanded="false" aria-controls="menu-mon-compte">Mon compte</button>
                                <div class="fr-collapse fr-menu" id="menu-mon-compte">
                                    <ul class="fr-menu__list">
                                        <li>
                                          <a class="fr-nav__link" href="{% url 'project:list' %}">Mes diagnostics</a>
                                        </li>
                                        <li>
                                            <a class="fr-nav__link" href="{% url 'users:profile' %}" target="_self">Profil</a>
                                        </li>


                                        {% if is_staff %}
                                        <li>
                                          <a class="fr-nav__link" href="{% url 'admin:index' %}">Administration</a>
                                        </li>
                                        <li>
                                          <a class="fr-nav__link" href="{% url 'public_data:matrix' %}">Matrice</a>
                                        </li>
                                        <li>
                                          <a class="fr-nav__link" href="{% url 'admin:diagnostic_word_wordtemplate_change' 'template-bilan-1' %}">Modèles Word du diagnostic</a>
                                        </li>
                                        <li>
                                          <a class="fr-nav__link" href="{% url 'home:all-emails' %}">Liste des e-mails</a>
                                        </li>
                                        <li>
                                          <a class="fr-nav__link" href="{% url 'project:excel' %}">Export Excel</a>
                                        </li>
                                        <li>
                                            <a class="fr-nav__link" href="{{ METABASE_URL }}" target="_blank">Metabase</a>
                                          </li>
                                        {% endif %}
                                        <li>
                                            <a class="fr-nav__link" href="{% url 'users:signout' %}" target="_self">Déconnexion</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            {% else %}
                            <li>
                                <a class="fr-btn" href="{% url 'users:signin' %}">
                                    Se connecter
                                </a>
                            </li>
                            <li>
                                <a class="fr-btn" href="{% url 'users:signup' %}">
                                    S’inscrire
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="fr-header__menu fr-modal" id="modal-499" aria-labelledby="button-500">
        <div class="fr-container">
            <button class="fr-btn--close fr-btn" aria-controls="modal-499" title="Fermer">
                Fermer
            </button>
            <div class="fr-header__menu-links">
            </div>
        </div>
    </div>
</header>

templates/index.html
{% load static %}
{% load utils_tags %}
{% load sri %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block pagetitle %}SPARTE{% endblock %}</title>

        <link crossorigin="anonymous" rel="icon" href="{% static 'favicon.ico' %}" integrity="sha256-17516aeae70e8509e89871d53bcf8a423dfa4d0c59d18a706d3046f4e6f513f7">
        <!-- Core theme CSS (includes Bootstrap)-->
        {% sri_static "bootstrap522/css/bootstrap.min.css" %}
        <!-- Bootstrap icon -->
        <link crossorigin="anonymous" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" integrity="sha256-8M+b2Hj+vy/2J5tZ9pYDHeuPD59KsaEZn1XXj3xVhjg=">
        <!-- Webpack Bundle CSS -->
        {% sri_static "assets/styles/main.css" %}
        <!-- subtemplate header injection -->
        {% block headers %}{% endblock %}
        <!-- matomo -->
        {% tracking_code %}
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <!-- Page content wrapper-->
        <div id="page-content-wrapper" class="d-flex flex-column h-100">
            <!-- Top navigation-->
            {% include "header.html" %}

            {% block breadcrumbs %}
            <div class="fr-container">
              <nav role="navigation" class="fr-breadcrumb" aria-label="vous êtes ici :">
                  <button class="fr-breadcrumb__button" aria-expanded="false" aria-controls="breadcrumb-1">Voir le fil d’Ariane</button>
                  <div class="fr-collapse" id="breadcrumb-1">
                      <ol class="fr-breadcrumb__list">
                        {% for bread in breadcrumbs %}
                            {% if bread.is_active %}
                            <li class="fr-breadcrumb__link" aria-current="page">{{ bread.title}}</li>
                            {% else %}
                            <li class="fr-breadcrumb__link"><a href="{{ bread.href }}">{{ bread.title}}</a></li>
                            {% endif %}
                        {% endfor %}
                      </ol>
                  </div>
              </nav>
            </div>
            {% endblock breadcrumbs %}

            <!-- Page content-->
            <main class="p-0 flex-grow-1 d-flex flex-column" id="main">
                {% if messages %}
                    <div class="row justify-content-center w-100 my-0 pt-3 pb-4">
                        <div class="col-12 col-md-8 col-lg-6">
                            {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-1" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                {% block carto %}
                <div id="block-content">
                    {% block content %}
                    {% endblock %}
                </div>
                {% endblock carto %}

                <!-- Footer-->
                {% block footer %}
                {% include "footer.html" %}
                {% endblock footer %}
                </div>
            </main>
        </div>

        {% sri_static "js/jquery-3.6.0.min.js" %}
        {% sri_static "bootstrap522/js/bootstrap.bundle.min.js" %}
        <!-- Webpack Bundle -->
        {% sri_static "assets/scripts/bundle.js" %}

        <script nonce="{{ CSP_NONCE }}">
        // initialize les tooltips
        $(function () {
            $('[data-toggle="tooltip"]').tooltip({
                trigger: 'hover'
            })
        })
        </script>
        <!-- subtemplate footer injection -->
        {% block bodyend %}{% endblock bodyend %}
        <!-- Tagging injection -->
        {% block tagging %}{% endblock tagging %}
        <script language="javascript" nonce="{{ CSP_NONCE }}">
            $( "#btn-documentation" ).click(function() {
                _paq.push(['trackEvent', 'Documentation', 'Barre de menu'])
            })
        </script>
    </body>
</html>